import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import Navbar from '@/components/Navbar';
import { cookies } from 'next/headers';
import ReduxProvider from '@/redux/Provider';
import SWRConfigContext from '@/context/SWRConfigContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    default: 'Dashboard',
    template: 'Dashboard | %s',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SWRConfigContext>
          <ReduxProvider>
            <section className="max-w-screen-lg 2xl:max-w-screen-2xl mx-auto px-2 flex flex-col min-h-screen">
              <nav className="flex justify-between py-4">
                <Navbar />
              </nav>
              <main className="grow">{children}</main>
            </section>
          </ReduxProvider>
        </SWRConfigContext>
      </body>
    </html>
  );
}
